In [131]:
def hello():
    print('Hello world')

In [132]:
print def()

SyntaxError: invalid syntax (<ipython-input-132-f85ad5942cb5>, line 1)

In [ ]:
hello ()

## Write A Function to add Two Numbers

In [ ]:
def addition(x,y): # Here x and Y are Parameters
    print(x+y)

In [133]:
addition (3,5) # Here x and y are arguments

NameError: name 'addition' is not defined

In [ ]:
def sleep_in (weekday,vacation):

## Exercise

# to display even numbers 1 to 10

In [ ]:
for num in range(1,10):
    if num % 2==0:
        print(num)

# while loop

## loop

In [ ]:
end = int(input('Enter range:'))
start = 1
while start <= end:
    if start % 3 == 0:
        print(start)
    start += 1 

In [ ]:
i = 1
while i < 6:
    print(i)
    i += 1

In [ ]:
i = 1
while i < 6:
    print(i)
    if i ==3:
        break
    i += 1

In [ ]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

### FOR Loop

In [ ]:
fruits = ['apple','banana','cherry']

In [ ]:
for x in fruits:
    print(x)

In [ ]:
for x in 'banana':   #Looping through a string
    print(x)

In [ ]:
fruits = ['apple','banana','cherry']   #Break statement
for x in fruits:
    print(x)
    if x == 'banana':
        break

In [ ]:
fruits = ['apple','banana','cherry']  #Continue statement
for x in fruits:
    if x == 'banana':
        continue
    print(x)

### Range() Function

In [134]:
for x in range(6):
    print(x)

0
1
2
3
4
5


In [135]:
for x in range(2,6):
    print(x)

2
3
4
5


In [136]:
for x in range(3,30,3):
    print(x)

3
6
9
12
15
18
21
24
27


In [137]:
for x in range(9):  #Else in loop
    print(x)
else:
    print('Cant Print above 9')

0
1
2
3
4
5
6
7
8
Cant Print above 9


### Nested Loops

In [138]:
adj = ['red','big','tasty']
fruits = ['apple','banana','cherry']

In [139]:
for x in adj:
    for y in fruits:
        print(x,y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


### Recursion

In [140]:
def tri_recursion(k):
    if (k>0):
        result = k+ tri_recursion(k-1)
        print(result)
    else:
        result = 0
    return result

print('Recursion results examples')
tri_recursion(5)

Recursion results examples
1
3
6
10
15


15

### Python Functions

In [141]:
def my_function():
    print('Hello from my function')

In [142]:
my_function()

Hello from my function


In [143]:
def my_function(country = 'India'):  # Default Parameter values
    print("I'm from " + country)

In [144]:
my_function('Sweden')

I'm from Sweden


In [145]:
my_function()

I'm from India


### Return Values

In [146]:
def my_function(x):
    return 5 * x

In [147]:
print(my_function(3))

15


In [148]:
def my_function(y):
    return 8 * y
print(my_function(3))

24


### Pyrhon Arrays

In [149]:
cars = ['Ford','Volvo','BMW'] #We HAve to Import Arrays

In [150]:
x = cars[0]
print(x)

Ford


In [151]:
cars[0] = "Toyota"

In [152]:
print(cars)

['Toyota', 'Volvo', 'BMW']


In [153]:
cars.append('Ford')

In [154]:
print(cars)

['Toyota', 'Volvo', 'BMW', 'Ford']


In [155]:
x = len(cars)
print(x)

4


In [156]:
cars.pop(1)
print(cars)

['Toyota', 'BMW', 'Ford']


In [157]:
cars.remove('BMW')
print(cars)

['Toyota', 'Ford']


### Dictionaries

In [158]:
my_dict = {1:'apple',2:'cherry',3:'banana'}

In [159]:
my_dict.keys()

dict_keys([1, 2, 3])

In [160]:
my_dict.values()

dict_values(['apple', 'cherry', 'banana'])

In [161]:
my_dict.items()

dict_items([(1, 'apple'), (2, 'cherry'), (3, 'banana')])

In [162]:
my_dict[3]

'banana'

In [163]:
my_dict.get(1)

'apple'

In [164]:
my_dict[4] = 'dog'

In [165]:
my_dict

{1: 'apple', 2: 'cherry', 3: 'banana', 4: 'dog'}

In [166]:
my_dict[2] = 'Bat'

In [167]:
my_dict

{1: 'apple', 2: 'Bat', 3: 'banana', 4: 'dog'}

#### EXAMPLES

##### PRIME NUMBER

In [168]:
n = int(input('Enter Number'))
if n>1:
    for x in range(2,n):
        if n%x ==0:
            print(n,'Number is Not Prime')
            break
        else:
            print(n,'Number is prime')
            break
else:
            print('Number is not prime')

KeyboardInterrupt: Interrupted by user

#### Palindrome sequence

In [ ]:
a = input('Enter sequence')
b = a[::-1]
if a == b:
    print('Palindrome')
else:
    print('Not a Palindrome')

#### Pyramids

In [ ]:
def func(r):
    for x in range(r):
        print(''*(r-x-1)+'*'*(2*x+1))

In [ ]:
func(4)

In [ ]:
def func(r):
    for x in range(r):
        print(' '*(r-x-1)+'*'*(2*x+1))
func(4)

In [ ]:
def func(r):
    for x in range(r):
        print('  '*(r-x-1)+'*'*(2*x+1))
func(4)

In [ ]:
n = int(input('Enter number'))
if n>1:
    for x in range(2,n):
        if n%x == 0:
            print('num is not prime')
            break
        else:
            print('Num is prime')
            break
else:
    print('num is not prime')

In [ ]:
a = input('Enter Sequence')
b = a[::-1]
if a == b:
    print('Palindrome')
else:
    print()

### Fibonacci series

In [ ]:
a = int(input('Enter number')) #Doubt End & next
f = 0
s = 1
if a<= 0:
    print('The Requested series is',f)
else:
    print(f,s)    #add end = ''
    for x in range(2,a):
        next = f+s
        print(next)
        f=s
        s=next
    

In [ ]:
lista = [33,43,2,2233,3]

In [ ]:
lista.sort()

In [ ]:
print(lista)

### Create a Vehicle class witht maax_speed and mileage instance attributes

In [ ]:
class Vehicle:
    def __init__(self,maxspeed,mileage):
        self.maxspeed = maxspeed
        self.mileage = mileage
    def info(self):
        print(f'The Car goes with a maximum speed of {self.maxspeed} and gives {self.mileage} kms Mileage')

In [ ]:
a = Vehicle('200','25')

In [ ]:
a.maxspeed

In [ ]:
a.info()

### Wap to print the fibonacci series till the nth value. take n from the user. example n = 5:
### output => 0,1,1,2,3 

In [ ]:
a = int(input('Enter the Number'))
f = 0
s = 1
if a <= 0:
    print('Not a Fibonacci series',f)
else:
    print(f,s)
    for x in range(2,a):
            value = f+s
            print(value)
            f = s
            s = value

In [ ]:
n = int(input('Enter the Number'))
a, b, c = 0, 1, 0
for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

### Try above problem using two variables

In [ ]:
a , b = 0, 1
for i in range(5):
    print(a)
    a, b = b, a+b

In [ ]:
def fibonacci():
    '''this is a Function to print fibonacci series. enter input as integer only.'''
    n = int(input('Enter the Number'))
    a,b =0,1
    if n <= 0:
        print('invalid Input')
    else:
        for i in range(n):
            print(a)
            a,b = b,a+b

In [ ]:
fibonacci.__doc__

### WAP to use a Function squares inside a new function which adds squares of threee numbers 

In [ ]:
def squares():  
    n = int(input('Enter the number'))
    for x in range(1,n +1):
        n = x * x
        print('square of x is ', n)

In [ ]:
squares()

In [ ]:
def squares(): # wrong
    n = int(input('Enter the number'))
    for x in range(1,n +1):
        n = x * x
        print(f'square of x is ', n)
def addition():
    n2 = int(input('Enter the number'))
    for i in range(1, n2+ 1):
        n = i * i
        n2 = n + n + n
        print(n2)

In [ ]:
addition()

In [ ]:
def squares(n):
    return n*n

In [ ]:
def squaresthree(a,b,c):
    return squares(a) + squares(b) + squares(c)

In [ ]:
squaresthree(2,3,4)

### 0^2 + (0^2 + 1^2) + (0^2 + 1^2 + 1^2) + ((0^2 + 1^2 + 1^2 + 2^2)...Print the nth summulation value for the given series

#### Lets get the summation of this => (0^2 + 1^2 + 1^2)

In [ ]:
n = int(input('enter the number'))
a , b = 0 , 1
for i in range(n):
    print(a)
    a, b = b, a+b

In [ ]:
n = 5
a,b = 0,1
for i in range(n):
    print(a**2)
    a, b = b, a+b

In [ ]:
n = 5
a, b = 0, 1
total = 0
for i in range(n):
    print('a is',a,'a square is',a**2)
    total = total + a**2
    a, b = b, a+b
print('total is',total)

In [ ]:
n = 5 
a, b = 0, 1
total = 0
ftotal = 0
for i in range(n):
    print('a is',a,'a square is',a**2)
    total = total + a**2
    ftotal = ftotal + total
    a,b = b, a+b
print('total is',total)
print('ftotal is',ftotal)

### For n = 5

In [ ]:
0**2 + (0**2 + 1**2) + (0**2 + 1**2 + 1**2) + (0**2 + 1**2 + 1**2 + 2**2) + (0**2 + 1**2 + 1**2 + 2**2 + 3**2)

In [ ]:
0 + 1 + 2 + 6 + 15

### WAP to ommit the first occurance of a charcter.string = 'Programming', char = 'r',output:'Pogramming'

In [ ]:
string = input('Enter a string')
char = input('enter char to be ommitted')
string2 = ''
for i in range(len(string)):
    if string[i] == char:
        string2 = string[0:i]+ string[i+1:]
        break
print(string2)

### WAP to print the fibonacci series 

In [ ]:
n = int(input('Enter the number'))
a = 0
b = 1
c = 0
for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

In [ ]:
n = 7
a, b = 0, 1
for i in range(n):
    print(a)
    a, b = b, a+b

In [ ]:
n = 5
a, b = 0, 1
for i in range(5):
    print(a)
    c = a + b
    a = b
    b = c

### Pyramids

In [ ]:
star = '*'
space = ' '
for i in range(1,6):
    print(star*i)

In [ ]:
n = int(input('Enter'))
star = '*'
space = ' '
for i in range(1, n + 1):
    print(star*i)

In [ ]:
n = 5
c = 0
while n > 0:
    print(' '* c + star*n)
    n = n - 1
    c += 1

In [ ]:
n = int(input('Enter Num'))
c = 0
while n > 0:
    print(' '* c + star*n)
    n = n - 1
    c += 1

In [ ]:
n = int(input("enter number"))
for i in range(n):
    print(i**2)

### leap year
### conditions are ;-
### The year can be evenly divided by 4, is a leap year, unless:
### The year can be evenly divided by 100, it is NOT a leap year, unless:
### The year is also evenly divisible by 400. Then it is a leap year.

In [ ]:
def leap(year):
    leap = False
    if year % 400 == 0:
        leap = True
    elif year % 4 == 0 and year % 100 != 0:
        leap = True
    return leap

In [ ]:
leap(1990)

In [ ]:
leap(2020)

### Question = Print the function

In [ ]:
n = int(input('enter number')) 
for i in range(1,n+1):
    print(i,end="")

### WAP to check wheather alphabet is vowel or consonant

In [ ]:
n = input('Enter Alphabet')
string = 'aeiou'
if n in string:
    print('Vowel')
else:
    print('Consonant')

In [ ]:
char = input('Enter any alphabet')
if char.isalpha():
    if char in 'aeiou':
        print('char is vowel')
    else:
        print('char is consonant')
else:
    print('Invalid Input')

In [ ]:
def vowelcheck():
    char = input('Enter any alphabet')
    if char.isalpha():
        if char in 'aeiou':
            print('char is vowel')
        else:
            print('char is consonant')
    else:
        print('Invalid Input')
        vowelcheck()

In [ ]:
vowelcheck()

In [ ]:
def vowelcheck2():
    vowel = 'aeiou'
    char = input('Enter alphabet')
    if char in vowel and char.isalpha():
        print('char is vowel')
    elif char is not vowel and char.isalpha():
        print('char is consonant')
    else:
        print('Invalid input')
        vowelcheck2

In [ ]:
vowelcheck2()

### write a function to check wheather a number is prime or not

In [ ]:
n =int(input('enter number'))
if n<1:
    for i in range(2,n):
        if n % i == 0:
            print(n,'number is not prime number')
            break
        else:
            print(n,'Number is  Prime number')
            break
else:
    print('Number is not a Prime number')

In [ ]:
def prime():
    n =int(input('enter number'))
    if n <= 1:
        print('enter value greater than 1')
        prime()
    else:
        for i in range(2,n):
            if n % i == 0:
                print(n,'number is not prime number')
                break
            else:
                print(n,'Number is  Prime number')
                break

In [ ]:
prime()

### Count the total number of digits given in a number

In [ ]:
num = int(input('enter number')) 
count = 0
while True:
    if num == 0:
        break
    else:
        num = num // 10
        count += 1
print('Number of digits in the entered number are',count)

## Database assignment

In [ ]:
import sqlite3

In [ ]:
db = sqlite3.connect('MyDB')

In [ ]:
cur = db.cursor()

In [ ]:
if cur.execute('DROP table if exists cartable'):
    print('table dropped successfully')

In [ ]:
if cur.execute('CREATE table cartable(id INTEGER primary key, name TEXT, colour TEXT)'):
    print('table executed')

In [ ]:
if cur.executemany('INSERT into cartable (name, colour) values(?,?)',[('BMW','BLACK'),('SWIFT','White'),('VOLKSWAGEN','BLUE')]):
    print('record 1,2,3 inserted sucessfully')

In [ ]:
db.commit()

In [ ]:
if cur.execute('SELECT name, colour from cartable '):
    print('selected')

In [ ]:
record = cur.fetchall()
print(record)

In [ ]:
cur.close()
db.close()

In [ ]:
import sqlite3

In [ ]:
db = sqlite3.connect('MyDB')

In [ ]:
cur = db.cursor()

In [ ]:
if cur.execute('SELECT * from cartable'):
    print('selected')

In [ ]:
for i in cur:
    print(i)

In [ ]:
cur.close()

In [ ]:
db.close()

In [ ]:
def passcheck(n):
    if n < 0:
        pass
    else:
        print('Pass works')

In [ ]:
passcheck(-3)

In [ ]:
def palindrome():
    a =input("Enter the Word ")
    b = a[::-1]
    if a == b:
        print('Palindrome')
    else:
        print('Not a Palindrome')

In [ ]:
palindrome()

In [ ]:
for i in range(1,10):
    print(i)

In [ ]:
for i in xrange(1,10):
    print(i)

In [ ]:
a = 15
b = 5
c = a//b
print(c)

In [ ]:
def palindrome():
    a = input('Enter a Sequence')
    b = a[::-1]
    if a == b:
        print("Palindrome")
    else:
        print('Not a Palindrome')

In [ ]:
palindrome()

In [ ]:
n = 
type(n)

In [ ]:
~12

In [ ]:
h = lambda x : x * x

In [ ]:
result = h(7)
print(result)

In [ ]:
class Carz():
    def __init__(self,model,colour,myear):
        self.model = model
        self.colour = colour
        self.myear = 1980

In [ ]:
c = Carz('Audi','Black',1980)

In [ ]:
c.model

In [ ]:
n = int(input('Enter number'))
if n>1:
    for x in range(2,n):
        if n%x == 0:
            print('num is not prime')
            break
        else:
            print('Num is prime')
            break
else:
    print('num is not prime')

In [ ]:
n = 10
for x in range(2,n):
    print(x)

In [ ]:
def prime():
    n = int(input("Enter the Number "))
    for i in range(2,n):
        if n % i == 0:
            print('Number is not a Prime Number')
            break
        else:
            print(n,'is a Prime Number')
            break

In [ ]:
prime()

In [ ]:
def prime():
    n = int(input('Enter the Number'))
    if n > 1:
        for i in range(2,n):
            if n%i == 0:
                print(n,'is not A Prime number')
                break
            else:
                print(n,'is a Prime number')
                break
    else:
        print('Number Should be Greater than 1')

In [ ]:
prime()

In [ ]:
def fibonacci():
    n = int(input("enter num"))
    a = 0
    b = 1
    c = 0
    for i in range(n):
        print(a)
        c = a + b
        a = b
        b = c

In [ ]:
fibonacci()

In [ ]:
def fib():
    n = 10
    a,b,c = 0,1,0
    for i in range(n):
        print(a)
        c = a + b
        a = b
        b = c
fib()

In [ ]:
n = int(input('Enter the Number'))
if n > 1:
    for i in range(2,n):
        if n % i ==0:
            print('Num is not Prime')
            break
        else:
            print('Num is a Prime')
            break
else:
    print('Num should be Greater than !')

In [ ]:
def palindrome():
    a = input('Enter a word')
    b = a[::-1]
    if a == b:
        print('Palindrome')
    else:
        print('Not a Palindrome')

In [ ]:
palindrome()

In [ ]:
while True:
    num = int(input('Enter the Num'))
    if num == 0:
        print('Num is Neither Odd nor Even')
    else:
        if num % 2 == 0:
            print("Number is even")
            break
        else:
            print('Num is Odd')
            break


In [ ]:
fact = 1
n = int(input("enter a number"))
for i in range(1,n+1):
    fact = fact * i
    print("factorial of num is ",fact)

In [ ]:
def primenum():
    n = int(input('Enter the Number'))
    if n > 1:
        for i in range(2,n):
            if n % i == 0:
                print("Not a Prime Number")
                break
            else:
                print(n,"is a Prime Number")
                break
    else:
        print('Number should be Greater than 1')
        
primenum()

In [ ]:
# ArmStrong Number

In [ ]:
num = int(input("Enter a Number"))
sum = 0
temp = s
while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp/=10
    
if num == sum:
    print('Armstrong Number')
else:
    print(num,'Not an Armstrong Number')

In [ ]:
# Python program to check if the number is an Armstrong number or not

# take input from the user
num = int(input("Enter a number: "))

# initialize sum
sum = 0

# find the sum of the cube of each digit
temp = num
while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10

# display the result
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")

In [ ]:
def primenum():
    n = int(input('Enter the Number'))
    if n > 1:
        for i in range(2,n):
            if n % i == 0:
                print("Not Prime Number")
                break
            else:
                print(n,"is a Prime Number")
                break
    else:
        print('Number should be Greater than 1')
        
primenum()

In [ ]:
lista = []
n = int(input('Enter a number'))
for i in range(n):
    lista.append(i)
    print(i*i)

In [ ]:
list3 = ['a','b','a','c','b']

In [ ]:
list3 = dict.fromkeys(list3)
print(list3)

In [ ]:
list3 = list(list3)

In [ ]:
list3

### Star Programs

In [176]:
num = int(input('Enter the num'))
for i in range(num):
    for j in range(num):
        print('*',end=' ')
    print()

Enter the num 5


* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [177]:
num = int(input('Enter the num'))
for i in range(num):
    print('* ' * num)

Enter the num 5


* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [178]:
n = int(input("Enter the num"))
for i in range(1,n+1):
    print('* '* i)

Enter the num 5


* 
* * 
* * * 
* * * * 
* * * * * 


In [179]:
num = int(input('Enter the number'))
for i in range(1,n+1):
    print('  '*(num-i)+ " *"* i)

Enter the number 5


         *
       * *
     * * *
   * * * *
 * * * * *


In [180]:
num = int(input('Enter the number'))
for i in range(1,num+1):
    print(' '*(num-i)+ " *"* i)

Enter the number 5


     *
    * *
   * * *
  * * * *
 * * * * *


In [181]:
num = int(input('Enter the number'))
for i in range(1,num+1):
    print(' '*(num-i)+ " *"* i)
for i in range(num,0,-1): # starting from num and ending with Zero with the difference of -1
    print(' '*(num-i)+ " *"* i)

Enter the number 5


     *
    * *
   * * *
  * * * *
 * * * * *
 * * * * *
  * * * *
   * * *
    * *
     *


In [182]:
num = int(input("Enter the number"))
for i in range(num,0,-1):
    print(' '*(num-i)+ " *"*i)

Enter the number 5


 * * * * *
  * * * *
   * * *
    * *
     *


In [183]:
num = int(input("Enter the number"))
for i in range(num,0,-1):
    print(" *"*i)

Enter the number 5


 * * * * *
 * * * *
 * * *
 * *
 *


### Exercise 1: Given two integer numbers return their product. If the product is greater than 1000, then return their sum

In [ ]:
def mul_sum():
    a = int(input('Enter the number'))
    b = int(input('Enter the second num'))
    product = a * b
    if product <= 1000:
        print('Result is',product)
    else:
        summ = a + b
        print('Result is',summ)

In [ ]:
mul_sum()

### Exercise 2: Given a range of the first 10 numbers, Iterate from the start number to the end number, and In each iteration print the sum of the current number and previous number

In [170]:
for i in range(0,10):
    p = 0
    prev = i
    curr = i +1
    summ = prev + curr
    print("prev num is ",prev,"current num",curr,'and sum is',summ)

prev num is  0 current num 1 and sum is 1
prev num is  1 current num 2 and sum is 3
prev num is  2 current num 3 and sum is 5
prev num is  3 current num 4 and sum is 7
prev num is  4 current num 5 and sum is 9
prev num is  5 current num 6 and sum is 11
prev num is  6 current num 7 and sum is 13
prev num is  7 current num 8 and sum is 15
prev num is  8 current num 9 and sum is 17
prev num is  9 current num 10 and sum is 19


In [171]:
prev = 0
curr = 0
for i in range(0,10):
    prev = curr
    curr = i
    summ = prev + i
    print("prev num is ",prev,"current num",i,'and sum is',summ)

prev num is  0 current num 0 and sum is 0
prev num is  0 current num 1 and sum is 1
prev num is  1 current num 2 and sum is 3
prev num is  2 current num 3 and sum is 5
prev num is  3 current num 4 and sum is 7
prev num is  4 current num 5 and sum is 9
prev num is  5 current num 6 and sum is 11
prev num is  6 current num 7 and sum is 13
prev num is  7 current num 8 and sum is 15
prev num is  8 current num 9 and sum is 17


### Exercise 3: Given a string, display only those characters which are present at an even index number.

In [190]:
strr = input('Enter text')
for i in range(len(strr)):
    if i % 2 == 0:
        print(strr[i],end= ' ')

Enter text notebook


n t b o 

In [210]:
str1 = input()
str[::2]

 rushi


'rsi'

### Exercise 4: Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string

In [228]:
char = input("Enter a word")
char1 = list(char)
cha = []
intt = int(input('Enter a num'))
for i in range(0,len(char1)):
    if i == intt:
#         a =char1[intt::]
#         print(a)
        a =char1[i::]
        cha.append(a)
        print(cha)

Enter a word bharath
Enter a num 3


[['r', 'a', 't', 'h']]


In [233]:
char = 'Gopi'
n = int(input("Num"))
a = char[n::]
print(a)

Num 2


pi


### Exercise 5: Given a list of numbers, return True if first and last number of a list is same

In [256]:
lista = [1,2,1,4,1]
a=lista[0]
if a == lista[-1]:    
    print("True")
else:
    print("False")

True


In [267]:
list1 = []
n1 = 0
while n1<5:
    n = int(input('Enter'))
    list1.append(n)
    n1+=1
    print(list1)
for i in list1:
    if list1[0] == list1[-1]:
        print("True")
        break
    else:
        print('False')
        break

Enter 1


[1]


Enter 2


[1, 2]


Enter 3


[1, 2, 3]


Enter 4


[1, 2, 3, 4]


Enter 1


[1, 2, 3, 4, 1]
True


In [268]:
import numpy as np

In [274]:
arr = np.array([])
arr

array([], dtype=float64)

In [278]:
arr = np.array([[1,2],[3,4],[5,6],[6,7]]) #Defining columns of each []

In [279]:
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [6 7]]


In [280]:
print(arr.shape)

(4, 2)


In [281]:
print(arr.ndim)

2


In [288]:
print(arr.itemsize)

8


In [289]:
arr1 = np.array([range(100,200,10)])

In [290]:
arr1

array([[100, 110, 120, 130, 140, 150, 160, 170, 180, 190]])

In [291]:
arr1.resize(5,2)

In [292]:
arr1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [293]:
arr3 = np.array([1,2,3,4,5,6,7,8])

In [294]:
arr3.resize(4,2)

In [295]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [296]:
arr3.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [298]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [299]:
print(sampleArray)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [304]:
sampleArray[0:3,2:3]

array([[33],
       [66],
       [99]])